// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenAmp.Infrastructure.Persistence;

#nullable disable

namespace OpenAmp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OpenAmpDbContext))]
    [Migration("20260724141935_Phase4DesktopOperations")]
    partial class Phase4DesktopOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpenAmp.Domain.Entities.Artikal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CijenaKupovine")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("InventarskiBroj")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("KategorijaArtiklaId")
                        .HasColumnType("int");

                    b.Property<int>("KolicinaNaStanju")
                        .HasColumnType("int");

                    b.Property<int>("MinimalnaZaliha")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Opis")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("StatusArtiklaId")
                        .HasColumnType("int");

                    b.Property<int>("StudioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventarskiBroj")
                        .IsUnique();

                    b.HasIndex("KategorijaArtiklaId");

                    b.HasIndex("StatusArtiklaId");

                    b.HasIndex("StudioId", "KolicinaNaStanju");

                    b.ToTable("Artikli", null, t =>
                        {
                            t.HasCheckConstraint("CK_Artikli_Cijena", "[CijenaKupovine] >= 0");

                            t.HasCheckConstraint("CK_Artikli_Zalihe", "[KolicinaNaStanju] >= 0 AND [MinimalnaZaliha] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CijenaKupovine = 15.00m,
                            InventarskiBroj = "ART-MO-0001",
                            KategorijaArtiklaId = 1,
                            KolicinaNaStanju = 20,
                            MinimalnaZaliha = 5,
                            Naziv = "Set žica 10-46",
                            Opis = "Set žica za električnu gitaru.",
                            StatusArtiklaId = 1,
                            StudioId = 1
                        },
                        new
                        {
                            Id = 2,
                            CijenaKupovine = 1.00m,
                            InventarskiBroj = "ART-MO-0002",
                            KategorijaArtiklaId = 2,
                            KolicinaNaStanju = 100,
                            MinimalnaZaliha = 20,
                            Naziv = "Trzalica 0.88 mm",
                            Opis = "Standardna najlonska trzalica.",
                            StatusArtiklaId = 1,
                            StudioId = 1
                        },
                        new
                        {
                            Id = 3,
                            CijenaKupovine = 6.00m,
                            InventarskiBroj = "ART-SA-0001",
                            KategorijaArtiklaId = 3,
                            KolicinaNaStanju = 30,
                            MinimalnaZaliha = 8,
                            Naziv = "9V baterija",
                            Opis = "Alkalna baterija za pedale.",
                            StatusArtiklaId = 1,
                            StudioId = 2
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Bend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FotografijaId")
                        .HasColumnType("int");

                    b.Property<string>("FotografijaUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("KreiranUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Opis")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("OsnivacId")
                        .HasColumnType("int");

                    b.Property<int>("ZanrId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FotografijaId");

                    b.HasIndex("Naziv");

                    b.HasIndex("OsnivacId");

                    b.HasIndex("ZanrId");

                    b.ToTable("Bendovi", (string)null);
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.ClanBenda", b =>
                {
                    b.Property<int>("BendId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DatumPridruzivanjaUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<string>("UlogaUBendu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BendId", "KorisnikId");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("ClanoviBenda", (string)null);
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Instrumenti", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kod = "VOKAL",
                            Naziv = "Vokal"
                        },
                        new
                        {
                            Id = 2,
                            Kod = "GITARA",
                            Naziv = "Gitara"
                        },
                        new
                        {
                            Id = 3,
                            Kod = "BAS",
                            Naziv = "Bas gitara"
                        },
                        new
                        {
                            Id = 4,
                            Kod = "BUBNJEVI",
                            Naziv = "Bubnjevi"
                        },
                        new
                        {
                            Id = 5,
                            Kod = "KLAVIJATURE",
                            Naziv = "Klavijature"
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.KategorijaArtikla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("KategorijeArtikala", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kod = "ZICE",
                            Naziv = "Žice"
                        },
                        new
                        {
                            Id = 2,
                            Kod = "TRZALICE",
                            Naziv = "Trzalice"
                        },
                        new
                        {
                            Id = 3,
                            Kod = "BATERIJE",
                            Naziv = "Baterije"
                        },
                        new
                        {
                            Id = 4,
                            Kod = "OSTALO",
                            Naziv = "Ostalo"
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.KategorijaOpreme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("KategorijeOpreme", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kod = "POJACALO",
                            Naziv = "Pojačalo"
                        },
                        new
                        {
                            Id = 2,
                            Kod = "MIKROFON",
                            Naziv = "Mikrofon"
                        },
                        new
                        {
                            Id = 3,
                            Kod = "INSTRUMENT",
                            Naziv = "Instrument"
                        },
                        new
                        {
                            Id = 4,
                            Kod = "KABLOVI",
                            Naziv = "Kablovi"
                        },
                        new
                        {
                            Id = 5,
                            Kod = "DODACI",
                            Naziv = "Dodaci"
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FotografijaUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("KreiranUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProfilnaSlikaId")
                        .HasColumnType("int");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UlogaId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProfilnaSlikaId");

                    b.HasIndex("StripeCustomerId")
                        .IsUnique()
                        .HasFilter("[StripeCustomerId] IS NOT NULL");

                    b.HasIndex("UlogaId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Korisnici", (string)null);
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.KorisnikInstrument", b =>
                {
                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<bool>("Primarni")
                        .HasColumnType("bit");

                    b.HasKey("KorisnikId", "InstrumentId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("KorisnikInstrumenti", (string)null);
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.MedijskaDatoteka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("KreiranaUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("KreiraoKorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("NazivDatoteke")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("Velicina")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("KreiraoKorisnikId", "KreiranaUtc");

                    b.ToTable("MedijskeDatoteke", null, t =>
                        {
                            t.HasCheckConstraint("CK_MedijskeDatoteke_Velicina", "[Velicina] > 0 AND [Velicina] <= 5242880");
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.OmiljenaSala", b =>
                {
                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KreiranaUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("KorisnikId", "SalaId");

                    b.HasIndex("SalaId");

                    b.HasIndex("KorisnikId", "KreiranaUtc");

                    b.ToTable("OmiljeneSale", (string)null);
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Oprema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CijenaNajmaPoSatu")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly?>("DatumNabavke")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DatumZadnjegServisa")
                        .HasColumnType("date");

                    b.Property<string>("InventarskiBroj")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("KategorijaOpremeId")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Opis")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("SalaId")
                        .HasColumnType("int");

                    b.Property<string>("SerijskiBroj")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Stanje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<int>("StatusOpremeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventarskiBroj")
                        .IsUnique();

                    b.HasIndex("SalaId");

                    b.HasIndex("StatusOpremeId");

                    b.HasIndex("KategorijaOpremeId", "StatusOpremeId", "SalaId");

                    b.ToTable("Oprema", null, t =>
                        {
                            t.HasCheckConstraint("CK_Oprema_CijenaNajma", "[CijenaNajmaPoSatu] >= 0");

                            t.HasCheckConstraint("CK_Oprema_Stanje", "[Stanje] BETWEEN 1 AND 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CijenaNajmaPoSatu = 5.00m,
                            DatumNabavke = new DateOnly(2025, 1, 15),
                            InventarskiBroj = "OPR-MO-0001",
                            KategorijaOpremeId = 1,
                            Naziv = "Marshall DSL40CR",
                            Opis = "Gitarsko cijevno pojačalo 40 W.",
                            SalaId = 1,
                            SerijskiBroj = "TEST-DSL40-001",
                            Stanje = 5,
                            StatusOpremeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CijenaNajmaPoSatu = 2.00m,
                            DatumNabavke = new DateOnly(2025, 2, 1),
                            InventarskiBroj = "OPR-MO-0002",
                            KategorijaOpremeId = 2,
                            Naziv = "Shure SM58",
                            Opis = "Dinamički vokalni mikrofon.",
                            SalaId = 1,
                            SerijskiBroj = "TEST-SM58-002",
                            Stanje = 5,
                            StatusOpremeId = 1
                        },
                        new
                        {
                            Id = 3,
                            CijenaNajmaPoSatu = 4.00m,
                            DatumNabavke = new DateOnly(2025, 3, 10),
                            InventarskiBroj = "OPR-SA-0001",
                            KategorijaOpremeId = 1,
                            Naziv = "Fender Rumble 100",
                            Opis = "Bas pojačalo 100 W.",
                            SalaId = 3,
                            SerijskiBroj = "TEST-RMB100-001",
                            Stanje = 4,
                            StatusOpremeId = 1
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.PostavkeKorisnika", b =>
                {
                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AzuriraneUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("EmailNotifikacije")
                        .HasColumnType("bit");

                    b.Property<string>("Jezik")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("ProfilJavan")
                        .HasColumnType("bit");

                    b.Property<bool>("PushNotifikacije")
                        .HasColumnType("bit");

                    b.HasKey("KorisnikId");

                    b.ToTable("PostavkeKorisnika", (string)null);
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.PozivnicaBenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BendId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsticeUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("KreiranaUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("OdgovorenaUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("PozvaniKorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("PozvaoKorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("StatusPozivniceId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.HasIndex("PozvaniKorisnikId");

                    b.HasIndex("PozvaoKorisnikId");

                    b.HasIndex("StatusPozivniceId");

                    b.HasIndex("BendId", "Username", "StatusPozivniceId");

                    b.ToTable("PozivniceBenda", null, t =>
                        {
                            t.HasCheckConstraint("CK_PozivniceBenda_Datum", "[IsticeUtc] > [KreiranaUtc]");
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Recenzija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Komentar")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KreiranaUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("Ocjena")
                        .HasColumnType("int");

                    b.Property<int?>("RezervacijaId")
                        .HasColumnType("int");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.Property<bool>("Vidljiva")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("RezervacijaId")
                        .IsUnique()
                        .HasFilter("[RezervacijaId] IS NOT NULL");

                    b.HasIndex("SalaId", "KreiranaUtc");

                    b.ToTable("Recenzije", null, t =>
                        {
                            t.HasCheckConstraint("CK_Recenzije_Ocjena", "[Ocjena] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("IsticeUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("KreiranSaIpAdrese")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("KreiranUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("OpozvanUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ZamijenjenTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("KorisnikId", "IsticeUtc");

                    b.ToTable("RefreshTokeni", null, t =>
                        {
                            t.HasCheckConstraint("CK_RefreshTokeni_Datum", "[IsticeUtc] > [KreiranUtc]");
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Rezervacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AzuriranaUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("BendId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KreiranaUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("KreiraoKorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("OtkazanaUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("RazlogOtkazivanja")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("RefundiranUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<decimal>("RefundiraniIznos")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.Property<int>("StatusRezervacijeId")
                        .HasColumnType("int");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StripeRefundId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("TerminDoUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("TerminOdUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<decimal>("UkupnaCijena")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("BendId");

                    b.HasIndex("KreiraoKorisnikId");

                    b.HasIndex("StatusRezervacijeId");

                    b.HasIndex("StripePaymentIntentId")
                        .IsUnique()
                        .HasFilter("[StripePaymentIntentId] IS NOT NULL");

                    b.HasIndex("SalaId", "TerminOdUtc", "TerminDoUtc")
                        .HasDatabaseName("IX_Rezervacije_Sala_Termin");

                    b.ToTable("Rezervacije", null, t =>
                        {
                            t.HasCheckConstraint("CK_Rezervacije_Cijena", "[UkupnaCijena] >= 0");

                            t.HasCheckConstraint("CK_Rezervacije_Termin", "[TerminDoUtc] > [TerminOdUtc]");
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Akustika")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("CijenaPoSatu")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("GeografskaDuzina")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("GeografskaSirina")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Opis")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int>("StatusSaleId")
                        .HasColumnType("int");

                    b.Property<int>("StudioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusSaleId");

                    b.HasIndex("StudioId", "Naziv")
                        .IsUnique();

                    b.ToTable("Sale", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sale_CijenaPoSatu", "[CijenaPoSatu] >= 0");

                            t.HasCheckConstraint("CK_Sale_Kapacitet", "[Kapacitet] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Akustika = "Akustički tretirana, kontrolisan niski spektar.",
                            CijenaPoSatu = 30.00m,
                            GeografskaDuzina = 17.8078m,
                            GeografskaSirina = 43.3438m,
                            Kapacitet = 6,
                            Naziv = "Marshall Room",
                            Opis = "Sala za rock i metal probe sa kompletnim backlineom.",
                            StatusSaleId = 1,
                            StudioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Akustika = "Topao, prirodan odjek pogodan za akustične instrumente.",
                            CijenaPoSatu = 24.00m,
                            GeografskaDuzina = 17.8078m,
                            GeografskaSirina = 43.3438m,
                            Kapacitet = 4,
                            Naziv = "Jazz Corner",
                            Opis = "Kompaktna sala sa toplijom akustikom za manje sastave.",
                            StatusSaleId = 1,
                            StudioId = 1
                        },
                        new
                        {
                            Id = 3,
                            Akustika = "Neutralna i dobro prigušena.",
                            CijenaPoSatu = 35.00m,
                            GeografskaDuzina = 18.4131m,
                            GeografskaSirina = 43.8563m,
                            Kapacitet = 8,
                            Naziv = "Stage A",
                            Opis = "Velika sala pogodna za kompletne bendove i pripremu nastupa.",
                            StatusSaleId = 1,
                            StudioId = 2
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.SalaSlika", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternativniTekst")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("MedijskaDatotekaId")
                        .HasColumnType("int");

                    b.Property<int>("Redoslijed")
                        .HasColumnType("int");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("MedijskaDatotekaId");

                    b.HasIndex("SalaId", "Redoslijed")
                        .IsUnique();

                    b.ToTable("SlikeSala", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlternativniTekst = "Marshall Room - glavni pogled",
                            Redoslijed = 1,
                            SalaId = 1,
                            Url = "https://example.openamp.local/images/marshall-room-1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            AlternativniTekst = "Jazz Corner - glavni pogled",
                            Redoslijed = 1,
                            SalaId = 2,
                            Url = "https://example.openamp.local/images/jazz-corner-1.jpg"
                        },
                        new
                        {
                            Id = 3,
                            AlternativniTekst = "Stage A - glavni pogled",
                            Redoslijed = 1,
                            SalaId = 3,
                            Url = "https://example.openamp.local/images/stage-a-1.jpg"
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.ServisOpreme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IzvrseniRadovi")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OpisKvara")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("OpremaId")
                        .HasColumnType("int");

                    b.Property<int>("PrijavioKorisnikId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrijavljenUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Trosak")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ZavrsenUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PrijavioKorisnikId");

                    b.HasIndex("OpremaId", "PrijavljenUtc");

                    b.ToTable("ServisiOpreme", null, t =>
                        {
                            t.HasCheckConstraint("CK_ServisiOpreme_Trosak", "[Trosak] >= 0");
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.StatusArtikla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("StatusiArtikala", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kod = "AKTIVAN",
                            Naziv = "Aktivan"
                        },
                        new
                        {
                            Id = 2,
                            Kod = "NEDOSTUPAN",
                            Naziv = "Nedostupan"
                        },
                        new
                        {
                            Id = 3,
                            Kod = "UKINUT",
                            Naziv = "Ukinut"
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.StatusOpreme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("StatusiOpreme", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kod = "DOSTUPNA",
                            Naziv = "Dostupna"
                        },
                        new
                        {
                            Id = 2,
                            Kod = "IZNAJMLJENA",
                            Naziv = "Iznajmljena"
                        },
                        new
                        {
                            Id = 3,
                            Kod = "SERVIS",
                            Naziv = "Na servisu"
                        },
                        new
                        {
                            Id = 4,
                            Kod = "POKVARENA",
                            Naziv = "Pokvarena"
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.StatusPozivnice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("StatusiPozivnica", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kod = "NA_CEKANJU",
                            Naziv = "Na čekanju"
                        },
                        new
                        {
                            Id = 2,
                            Kod = "PRIHVACENA",
                            Naziv = "Prihvaćena"
                        },
                        new
                        {
                            Id = 3,
                            Kod = "ODBIJENA",
                            Naziv = "Odbijena"
                        },
                        new
                        {
                            Id = 4,
                            Kod = "ISTEKLA",
                            Naziv = "Istekla"
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.StatusRezervacije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("StatusiRezervacija", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kod = "NA_CEKANJU",
                            Naziv = "Na čekanju"
                        },
                        new
                        {
                            Id = 2,
                            Kod = "PLACENA",
                            Naziv = "Plaćena"
                        },
                        new
                        {
                            Id = 3,
                            Kod = "IZVRSENA",
                            Naziv = "Izvršena"
                        },
                        new
                        {
                            Id = 4,
                            Kod = "OTKAZANA",
                            Naziv = "Otkazana"
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.StatusSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("StatusiSala", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kod = "AKTIVNA",
                            Naziv = "Aktivna"
                        },
                        new
                        {
                            Id = 2,
                            Kod = "ODRZAVANJE",
                            Naziv = "Na održavanju"
                        },
                        new
                        {
                            Id = 3,
                            Kod = "NEAKTIVNA",
                            Naziv = "Neaktivna"
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.StavkaRezervacije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArtikalId")
                        .HasColumnType("int");

                    b.Property<decimal>("BrojSati")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("JedinicnaCijena")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("OpremaId")
                        .HasColumnType("int");

                    b.Property<int>("RezervacijaId")
                        .HasColumnType("int");

                    b.Property<decimal>("UkupnaCijena")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ArtikalId");

                    b.HasIndex("OpremaId");

                    b.HasIndex("RezervacijaId", "OpremaId");

                    b.ToTable("StavkeRezervacija", null, t =>
                        {
                            t.HasCheckConstraint("CK_StavkeRezervacija_Cijene", "[JedinicnaCijena] >= 0 AND [BrojSati] >= 0 AND [UkupnaCijena] >= 0");

                            t.HasCheckConstraint("CK_StavkeRezervacija_Kolicina", "[Kolicina] > 0");

                            t.HasCheckConstraint("CK_StavkeRezervacija_Tip", "([OpremaId] IS NOT NULL AND [ArtikalId] IS NULL) OR ([OpremaId] IS NULL AND [ArtikalId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.StripeWebhookDogadjaj", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ObradjenUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("StripeWebhookDogadjaji", (string)null);
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<int>("DjelimicniPovratDoSati")
                        .HasColumnType("int");

                    b.Property<int>("DjelimicniPovratPostotak")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int?>("FotografijaId")
                        .HasColumnType("int");

                    b.Property<string>("FotografijaUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Opis")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int>("PuniPovratDoSati")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("RadnoVrijemeDo")
                        .HasColumnType("time(0)");

                    b.Property<TimeOnly>("RadnoVrijemeOd")
                        .HasColumnType("time(0)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("VlasnikId")
                        .HasColumnType("int");

                    b.Property<string>("VremenskaZona")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FotografijaId");

                    b.HasIndex("VlasnikId");

                    b.HasIndex("Grad", "Naziv");

                    b.ToTable("Studiji", null, t =>
                        {
                            t.HasCheckConstraint("CK_Studiji_PovratPostotak", "[DjelimicniPovratPostotak] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Studiji_PovratSati", "[PuniPovratDoSati] >= [DjelimicniPovratDoSati] AND [DjelimicniPovratDoSati] >= 0");

                            t.HasCheckConstraint("CK_Studiji_RadnoVrijeme", "[RadnoVrijemeDo] > [RadnoVrijemeOd]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresa = "Kneza Višeslava 10",
                            Aktivan = true,
                            DjelimicniPovratDoSati = 12,
                            DjelimicniPovratPostotak = 50,
                            Email = "mostar@example.openamp.local",
                            Grad = "Mostar",
                            Naziv = "OpenAmp Mostar",
                            Opis = "Testni studio za razvoj i demonstraciju sistema.",
                            PuniPovratDoSati = 24,
                            RadnoVrijemeDo = new TimeOnly(23, 0, 0),
                            RadnoVrijemeOd = new TimeOnly(8, 0, 0),
                            Telefon = "+387 36 000 001",
                            VremenskaZona = "Europe/Sarajevo"
                        },
                        new
                        {
                            Id = 2,
                            Adresa = "Zmaja od Bosne 20",
                            Aktivan = true,
                            DjelimicniPovratDoSati = 12,
                            DjelimicniPovratPostotak = 50,
                            Email = "sarajevo@example.openamp.local",
                            Grad = "Sarajevo",
                            Naziv = "OpenAmp Sarajevo",
                            Opis = "Drugi testni studio za provjeru rada sa više lokacija.",
                            PuniPovratDoSati = 24,
                            RadnoVrijemeDo = new TimeOnly(23, 0, 0),
                            RadnoVrijemeOd = new TimeOnly(8, 0, 0),
                            Telefon = "+387 33 000 002",
                            VremenskaZona = "Europe/Sarajevo"
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Uloga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Uloge", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kod = "ADMIN",
                            Naziv = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Kod = "ZAPOSLENIK",
                            Naziv = "Zaposlenik"
                        },
                        new
                        {
                            Id = 3,
                            Kod = "MUZICAR",
                            Naziv = "Muzičar"
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Zanr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Zanrovi", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kod = "ROCK",
                            Naziv = "Rock"
                        },
                        new
                        {
                            Id = 2,
                            Kod = "METAL",
                            Naziv = "Metal"
                        },
                        new
                        {
                            Id = 3,
                            Kod = "JAZZ",
                            Naziv = "Jazz"
                        },
                        new
                        {
                            Id = 4,
                            Kod = "POP",
                            Naziv = "Pop"
                        },
                        new
                        {
                            Id = 5,
                            Kod = "FUNK",
                            Naziv = "Funk"
                        });
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Artikal", b =>
                {
                    b.HasOne("OpenAmp.Domain.Entities.KategorijaArtikla", "Kategorija")
                        .WithMany("Artikli")
                        .HasForeignKey("KategorijaArtiklaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenAmp.Domain.Entities.StatusArtikla", "Status")
                        .WithMany("Artikli")
                        .HasForeignKey("StatusArtiklaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenAmp.Domain.Entities.Studio", "Studio")
                        .WithMany("Artikli")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategorija");

                    b.Navigation("Status");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Bend", b =>
                {
                    b.HasOne("OpenAmp.Domain.Entities.MedijskaDatoteka", "Fotografija")
                        .WithMany()
                        .HasForeignKey("FotografijaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenAmp.Domain.Entities.Korisnik", "Osnivac")
                        .WithMany("OsnovaniBendovi")
                        .HasForeignKey("OsnivacId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenAmp.Domain.Entities.Zanr", "Zanr")
                        .WithMany("Bendovi")
                        .HasForeignKey("ZanrId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fotografija");

                    b.Navigation("Osnivac");

                    b.Navigation("Zanr");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.ClanBenda", b =>
                {
                    b.HasOne("OpenAmp.Domain.Entities.Bend", "Bend")
                        .WithMany("Clanovi")
                        .HasForeignKey("BendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenAmp.Domain.Entities.Instrument", "Instrument")
                        .WithMany("ClanoviBendova")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpenAmp.Domain.Entities.Korisnik", "Korisnik")
                        .WithMany("Clanstva")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bend");

                    b.Navigation("Instrument");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Korisnik", b =>
                {
                    b.HasOne("OpenAmp.Domain.Entities.MedijskaDatoteka", "ProfilnaSlika")
                        .WithMany()
                        .HasForeignKey("ProfilnaSlikaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenAmp.Domain.Entities.Uloga", "Uloga")
                        .WithMany("Korisnici")
                        .HasForeignKey("UlogaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProfilnaSlika");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.KorisnikInstrument", b =>
                {
                    b.HasOne("OpenAmp.Domain.Entities.Instrument", "Instrument")
                        .WithMany("Korisnici")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenAmp.Domain.Entities.Korisnik", "Korisnik")
                        .WithMany("Instrumenti")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.MedijskaDatoteka", b =>
                {
                    b.HasOne("OpenAmp.Domain.Entities.Korisnik", "KreiraoKorisnik")
                        .WithMany()
                        .HasForeignKey("KreiraoKorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KreiraoKorisnik");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.OmiljenaSala", b =>
                {
                    b.HasOne("OpenAmp.Domain.Entities.Korisnik", "Korisnik")
                        .WithMany("OmiljeneSale")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenAmp.Domain.Entities.Sala", "Sala")
                        .WithMany("Favoriti")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Oprema", b =>
                {
                    b.HasOne("OpenAmp.Domain.Entities.KategorijaOpreme", "Kategorija")
                        .WithMany("Oprema")
                        .HasForeignKey("KategorijaOpremeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenAmp.Domain.Entities.Sala", "Sala")
                        .WithMany("Oprema")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenAmp.Domain.Entities.StatusOpreme", "Status")
                        .WithMany("Oprema")
                        .HasForeignKey("StatusOpremeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategorija");

                    b.Navigation("Sala");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.PostavkeKorisnika", b =>
                {
                    b.HasOne("OpenAmp.Domain.Entities.Korisnik", "Korisnik")
                        .WithOne("Postavke")
                        .HasForeignKey("OpenAmp.Domain.Entities.PostavkeKorisnika", "KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.PozivnicaBenda", b =>
                {
                    b.HasOne("OpenAmp.Domain.Entities.Bend", "Bend")
                        .WithMany("Pozivnice")
                        .HasForeignKey("BendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenAmp.Domain.Entities.Korisnik", "PozvaniKorisnik")
                        .WithMany("PrimljenePozivnice")
                        .HasForeignKey("PozvaniKorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenAmp.Domain.Entities.Korisnik", "PozvaoKorisnik")
                        .WithMany("PoslanePozivnice")
                        .HasForeignKey("PozvaoKorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenAmp.Domain.Entities.StatusPozivnice", "Status")
                        .WithMany("Pozivnice")
                        .HasForeignKey("StatusPozivniceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bend");

                    b.Navigation("PozvaniKorisnik");

                    b.Navigation("PozvaoKorisnik");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Recenzija", b =>
                {
                    b.HasOne("OpenAmp.Domain.Entities.Korisnik", "Korisnik")
                        .WithMany("Recenzije")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenAmp.Domain.Entities.Rezervacija", "Rezervacija")
                        .WithOne("Recenzija")
                        .HasForeignKey("OpenAmp.Domain.Entities.Recenzija", "RezervacijaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpenAmp.Domain.Entities.Sala", "Sala")
                        .WithMany("Recenzije")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Rezervacija");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("OpenAmp.Domain.Entities.Korisnik", "Korisnik")
                        .WithMany("RefreshTokeni")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Rezervacija", b =>
                {
                    b.HasOne("OpenAmp.Domain.Entities.Bend", "Bend")
                        .WithMany("Rezervacije")
                        .HasForeignKey("BendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenAmp.Domain.Entities.Korisnik", "KreiraoKorisnik")
                        .WithMany("KreiraneRezervacije")
                        .HasForeignKey("KreiraoKorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenAmp.Domain.Entities.Sala", "Sala")
                        .WithMany("Rezervacije")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenAmp.Domain.Entities.StatusRezervacije", "Status")
                        .WithMany("Rezervacije")
                        .HasForeignKey("StatusRezervacijeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bend");

                    b.Navigation("KreiraoKorisnik");

                    b.Navigation("Sala");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Sala", b =>
                {
                    b.HasOne("OpenAmp.Domain.Entities.StatusSale", "Status")
                        .WithMany("Sale")
                        .HasForeignKey("StatusSaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenAmp.Domain.Entities.Studio", "Studio")
                        .WithMany("Sale")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.SalaSlika", b =>
                {
                    b.HasOne("OpenAmp.Domain.Entities.MedijskaDatoteka", "MedijskaDatoteka")
                        .WithMany()
                        .HasForeignKey("MedijskaDatotekaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenAmp.Domain.Entities.Sala", "Sala")
                        .WithMany("Galerija")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedijskaDatoteka");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.ServisOpreme", b =>
                {
                    b.HasOne("OpenAmp.Domain.Entities.Oprema", "Oprema")
                        .WithMany("ServisnaHistorija")
                        .HasForeignKey("OpremaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenAmp.Domain.Entities.Korisnik", "PrijavioKorisnik")
                        .WithMany("PrijavljeniServisi")
                        .HasForeignKey("PrijavioKorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Oprema");

                    b.Navigation("PrijavioKorisnik");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.StavkaRezervacije", b =>
                {
                    b.HasOne("OpenAmp.Domain.Entities.Artikal", "Artikal")
                        .WithMany("StavkeRezervacija")
                        .HasForeignKey("ArtikalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpenAmp.Domain.Entities.Oprema", "Oprema")
                        .WithMany("StavkeRezervacija")
                        .HasForeignKey("OpremaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpenAmp.Domain.Entities.Rezervacija", "Rezervacija")
                        .WithMany("Stavke")
                        .HasForeignKey("RezervacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("Oprema");

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Studio", b =>
                {
                    b.HasOne("OpenAmp.Domain.Entities.MedijskaDatoteka", "Fotografija")
                        .WithMany()
                        .HasForeignKey("FotografijaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenAmp.Domain.Entities.Korisnik", "Vlasnik")
                        .WithMany("Studiji")
                        .HasForeignKey("VlasnikId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Fotografija");

                    b.Navigation("Vlasnik");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Artikal", b =>
                {
                    b.Navigation("StavkeRezervacija");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Bend", b =>
                {
                    b.Navigation("Clanovi");

                    b.Navigation("Pozivnice");

                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Instrument", b =>
                {
                    b.Navigation("ClanoviBendova");

                    b.Navigation("Korisnici");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.KategorijaArtikla", b =>
                {
                    b.Navigation("Artikli");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.KategorijaOpreme", b =>
                {
                    b.Navigation("Oprema");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Korisnik", b =>
                {
                    b.Navigation("Clanstva");

                    b.Navigation("Instrumenti");

                    b.Navigation("KreiraneRezervacije");

                    b.Navigation("OmiljeneSale");

                    b.Navigation("OsnovaniBendovi");

                    b.Navigation("PoslanePozivnice");

                    b.Navigation("Postavke");

                    b.Navigation("PrijavljeniServisi");

                    b.Navigation("PrimljenePozivnice");

                    b.Navigation("Recenzije");

                    b.Navigation("RefreshTokeni");

                    b.Navigation("Studiji");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Oprema", b =>
                {
                    b.Navigation("ServisnaHistorija");

                    b.Navigation("StavkeRezervacija");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Rezervacija", b =>
                {
                    b.Navigation("Recenzija");

                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Sala", b =>
                {
                    b.Navigation("Favoriti");

                    b.Navigation("Galerija");

                    b.Navigation("Oprema");

                    b.Navigation("Recenzije");

                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.StatusArtikla", b =>
                {
                    b.Navigation("Artikli");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.StatusOpreme", b =>
                {
                    b.Navigation("Oprema");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.StatusPozivnice", b =>
                {
                    b.Navigation("Pozivnice");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.StatusRezervacije", b =>
                {
                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.StatusSale", b =>
                {
                    b.Navigation("Sale");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Studio", b =>
                {
                    b.Navigation("Artikli");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Uloga", b =>
                {
                    b.Navigation("Korisnici");
                });

            modelBuilder.Entity("OpenAmp.Domain.Entities.Zanr", b =>
                {
                    b.Navigation("Bendovi");
                });
#pragma warning restore 612, 618
        }
    }
}
