<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\OpenAmp.Application\OpenAmp.Application.csproj" />
    <ProjectReference Include="..\OpenAmp.Infrastructure\OpenAmp.Infrastructure.csproj" />
    <ProjectReference Include="..\OpenAmp.Domain\OpenAmp.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.29" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="8.0.29" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>be233c6d-05d1-4802-9463-3bd21556ad34</UserSecretsId>
  </PropertyGroup>

</Project>
